old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'

    producers:
        image_processing:
            connection:       default
            exchange_options: { name: 'image_processing_ex', type: fanout }
    consumers:
        image_processing:
            connection:       default
            exchange_options: { name: 'image_processing_ex', type: fanout }
            queue_options:    { name: 'image_processing_qu'}
            callback:          LaSalle\Rendimiento\JudithVilela\Shared\Infrastructure\RabbitMq\RabbitMqConsumer
